import type { Metadata } from "next";
import { figtree, inter } from "@/Lib/fonts";
import "./globals.css";


export const metadata: Metadata = {
  title: "FriendsCodes - Benefit from referrals!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${figtree.variable} ${inter.variable} scroll-smooth`}>
      <body className="font-figtree bg-[#09071C] overflow-x-hidden overflow-y-scroll">
        {children}
      </body>
    </html>
  );
}
